@url = http://localhost:3000/api 
@json = Content-Type: application/json
### 
get {{url}}
### 注册
post {{url}}/register 
{{json}}

{
    "username": "fangyong",
    "password": "F1234567"
}
### 登录
post {{url}}/login
{{json}}

{
    "username": "fangyong",
    "password": "F1234567"
}
### 用户列表
get {{url}}/users
### 个人信息
get {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZTZjYmJhZjEzNGY4ODQyZjdkZGUyYyIsImlhdCI6MTU1ODYyOTk3Nn0.ENqDmNC4YBm5czYe92alChluQQgMqIAldy2f9N2ohlg