@url = http://localhost:3000/api 
@json = Content-Type: application/json
### 
get {{url}}
### 注册
post {{url}}/register 
{{json}}

{
    "username": "fangyong",
    "password": "F1234567"
}
### 登录
post {{url}}/login
{{json}}

{
    "username": "fangyong",
    "password": "F1234567"
}
### 用户列表
get {{url}}/users
### 个人信息
get {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZTZjYmJhZjEzNGY4ODQyZjdkZGUyYyIsImV4cCI6MTU1ODY2NDAwMSwiaWF0IjoxNTU4NjYzOTcxfQ.tox9VRx_2_mK2d4Vos5_D-meAttMMch6WUGNTTfhze4